language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on

# Override the base install phase so that the project can be installed using
# `-mod=vendor` to use the vendored dependencies
install:
  - go install -v -race -mod=vendor ./...

script:
  - go vet ./...
  - go test -v -mod=vendor ./...
