language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on

# Override the base install phase so that the project can be installed using
# `-mod=vendor` to use the vendored dependencies
install:
  - go -mod=vendor install -v -race ./...

script:
  - go -mod=vendor vet -v ./...
  - go -mod=vendor test -v -race ./...
